name: Run Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: '3.9'
          conda-channels: anaconda, conda-forge
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install -e .
          pip install coveralls
          conda install -c conda-forge graph-tool
      - name: Run Tests
        run: |
          cd tests
          coverage run --source=kgtk --debug=trace -m unittest discover      
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          coveralls --service=github
